# Generated by Django 3.1.5 on 2021-01-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_auto_20210111_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_list',
            field=models.CharField(default='', max_length=200),
        ),
    ]
