# Generated by Django 3.1.5 on 2021-01-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0004_auto_20210111_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_list',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_list_id',
            field=models.IntegerField(default=0),
        ),
    ]
