# Generated by Django 3.1.5 on 2021-01-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_auto_20210110_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
