# Generated by Django 3.1.5 on 2021-01-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0003_remove_task_priotiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priotiy',
            field=models.IntegerField(default=0),
        ),
    ]
