# Generated by Django 3.1.5 on 2021-01-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0004_task_priotiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priotiy',
        ),
    ]
